### ISSUE TITLE
VS Code remote SSH > fix

### ISSUE THREAD

**Issue by p3dro114** [HybridDevTools/d3nver#31]
To use VSCode with remote SSH connexion on D3nver you need add those mising packages :

`-rw-r--r-- 1 root root    313 Mar 21 23:40 /var/lib/dpkg/info/gcc-8-base:amd64.list
-rw-r--r-- 1 root root    716 Mar 21 23:40 /var/lib/dpkg/info/libstdc++6:amd64.list
-rw-r--r-- 1 root root    205 Mar 21 23:40 /var/lib/dpkg/info/libgcc1:amd64.list
-rw-r--r-- 1 root root   1188 Mar 21 23:47 /var/lib/dpkg/info/xz-utils.list
-rw-r--r-- 1 root root  28460 Mar 21 23:47 /var/lib/dpkg/info/glibc-source.list`

Without this fix, VSCode remote ssh won't work.

PS : VSCode on Windows machine

**Comment by Hybrid512** [comment]
Closed and moved to https://github.com/HybridDevTools/d3nver-rbi-builder
